title: Pixusa
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://pixusa.eu" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Timea Szili # add your name
author-pic: szt.jpg
about-author: >
  My name is Timea.
  
# Contact links
website: www.pixusa.eu # Add your website, do not add http://
github: PixieBurger # Add your Github handle
twitter: '@timeaszili' # Add your Twitter handle

# Newsletter
#mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: gone-cycling # Add your discus identifier

# Tracker
analytics: UA-49032236-5 # Google Analytics

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
